### ISSUE TITLE
Tree structure serialization problem

### ISSUE THREAD

**Issue by sugatov** [opensoft/simple-serializer#9]
Hello!
I'm have the following class metadata:

``` yaml
Entities\EventCategory:
    properties:
        id:
            expose: true
            type: integer
            groups: ['up', 'down']
        name:
            expose: true
            type: string
            groups: ['up', 'down']
        parent:
            expose: true
            type: \Entities\EventCategory
            groups: ['up']
        children:
            expose: true
            type: array
            groups: ['down']
```

I'm getting this while trying to serialize a tree in any way:

```
Fatal error: Maximum function nesting level of '100' reached, aborting!
```

Is this an expected result? I missed something? Can you help please?

upd: Indeed, I missed something. Resolved.
